name: lapor_pak_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

    
  
  # iOS style icons
  cupertino_icons: ^1.0.8
  
  # HTTP & API
  http: ^1.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Image Picker
  image_picker: ^1.0.7
  
  # Intl (untuk format tanggal)
  intl: ^0.19.0
  
  # Loading & Toast
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true